Vagrant.configure(2) do |config|

	config.vm.box_check_update = false
	config.vm.box = "centos/8"

	config.vm.define "odhazzarS" do |s|
		s.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
			v.customize ["modifyvm", :id, "--name", "odhazzarS", "--natdnsproxy1", "on", "--natdnshostresolver1", "on"]
		end

		s.vm.network :private_network, ip: "192.168.42.110"
		s.vm.hostname = "odhazzarS"
		s.vm.provision "shell", privileged: true, path: "scripts/server.sh"
	end
end
